<?php
/**
 * @file
 * Install schema for the arbitrary pair module
 */

/**
 * Implements hook_schema().
 */
function tlppair_field_schema ($field) {
  return array(
    'columns' => array(
      'tlppair_val_1' => array(
        'type'     => 'varchar',
        'length'   => 255,
        'not null' => FALSE,
      ),
      'tlppair_val_2' => array(
        'type'     => 'varchar',
        'length'   => 255,
        'not null' => FALSE,
      ),
    ),
  );
}
